name: .NET

on:
  push:
    branches:
      - bepinex

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup.NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Pack
        run: dotnet pack --no-build -c Release

      - name: Publish
        run: dotnet nuget push ./bin/Release/*.nupkg -s https://nuget.kiraihooks.me/v3/index.json -k ${{ secrets.NUGET_KIRAIHOOKS_ME_KEY }}
