name: .NET

on:
  push:
    branches:
      - bepinex

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Pack
        run: dotnet pack --no-build -c Release

      - name: Publish
        run: dotnet nuget push ./bin/Release/*.nupkg -s https://nuget.kiraihooks.me/v3/index.json -k ${{ secrets.NUGET_KIRAIHOOKS_ME_KEY }}

      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::Build_$(date +"%Y.%m.%d_%H-%M")"

      - name: Publish a release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: |
            bin/Release/netstandard2.1/WingAPI.dll
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
